import './BrainBoard.css'
import { createDiv } from '../../TicTacToe/CreateDiv'
export const initBrainBoard = () => {
  const board = createDiv('boardBrain')
  board.classList.add('hide')
  /* create 4x4 grid */
  const cell0_0 = createDiv('cellGame', '0_0')
  const cell0_1 = createDiv('cellGame', '0_1')
  const cell0_2 = createDiv('cellGame', '0_2')
  const cell0_3 = createDiv('cellGame', '0_3')
  const cell1_0 = createDiv('cellGame', '1_0')
  const cell1_1 = createDiv('cellGame', '1_1')
  const cell1_2 = createDiv('cellGame', '1_2')
  const cell1_3 = createDiv('cellGame', '1_3')
  const cell2_0 = createDiv('cellGame', '2_0')
  const cell2_1 = createDiv('cellGame', '2_1')
  const cell2_2 = createDiv('cellGame', '2_2')
  const cell2_3 = createDiv('cellGame', '2_3')
  const cell3_0 = createDiv('cellGame', '3_0')
  const cell3_1 = createDiv('cellGame', '3_1')
  const cell3_2 = createDiv('cellGame', '3_2')
  const cell3_3 = createDiv('cellGame', '3_3')
  board.append(cell0_0)
  board.append(cell0_1)
  board.append(cell0_2)
  board.append(cell0_3)
  board.append(cell1_0)
  board.append(cell1_1)
  board.append(cell1_2)
  board.append(cell1_3)
  board.append(cell2_0)
  board.append(cell2_1)
  board.append(cell2_2)
  board.append(cell2_3)
  board.append(cell3_0)
  board.append(cell3_1)
  board.append(cell3_2)
  board.append(cell3_3)
  return board
}
